export const categoryColorMap: Record<string, string> = {
  'Business Strategy & Operations': '#6366f1',
  'Career & Job Search':            '#8b5cf6',
  'Content & Writing':              '#06b6d4',
  'Engineering & Product':          '#10b981',
  'Excel & Data':                   '#22c55e',
  'Freelancing & Business Building':'#f59e0b',
  'Investing & Finance':            '#3b82f6',
  'Learning & Self-Development':    '#a78bfa',
  'Legal':                          '#94a3b8',
  'Marketing & SEO':                '#f97316',
  'Personal Finance':               '#0ea5e9',
  'Presentations':                  '#ec4899',
  'Productivity & Automation':      '#14b8a6',
  'Research & Analysis':            '#84cc16',
  'Notebooks':                      '#d946ef',
  'Competitive Analysis':           '#ef4444',
  'Travel':                         '#fb923c',
  'Meeting Recordings':             '#38bdf8',
  'Personal Productivity':          '#a3e635',
  'Cowork':                         '#818cf8',
}

export const toolColorMap: Record<string, string> = {
  'Copilot Chat':  '#6366f1',
  'Excel':         '#22c55e',
  'Word':          '#3b82f6',
  'Teams':         '#8b5cf6',
  'PowerPoint':    '#f97316',
  'Outlook':       '#06b6d4',
  'Notebooks':     '#d946ef',
  'Cowork':        '#818cf8',
  'Researcher':    '#f59e0b',
  'Any AI Tool':   '#94a3b8',
}

export const categories = [
  { name: 'Business Strategy & Operations', slug: 'business-strategy',     icon: 'Building2',     count: 22 },
  { name: 'Career & Job Search',            slug: 'career',                icon: 'Briefcase',     count: 16 },
  { name: 'Content & Writing',              slug: 'content-writing',       icon: 'PenLine',       count: 25 },
  { name: 'Engineering & Product',          slug: 'engineering',           icon: 'Code2',         count: 14 },
  { name: 'Excel & Data',                   slug: 'excel-data',            icon: 'BarChart3',     count: 15 },
  { name: 'Freelancing & Business Building',slug: 'freelancing',           icon: 'Rocket',        count: 16 },
  { name: 'Investing & Finance',            slug: 'investing',             icon: 'TrendingUp',    count: 27 },
  { name: 'Learning & Self-Development',    slug: 'learning',              icon: 'GraduationCap', count: 6  },
  { name: 'Legal',                          slug: 'legal',                 icon: 'Scale',         count: 6  },
  { name: 'Marketing & SEO',                slug: 'marketing',             icon: 'Megaphone',     count: 15 },
  { name: 'Personal Finance',               slug: 'personal-finance',      icon: 'Wallet',        count: 18 },
  { name: 'Presentations',                  slug: 'presentations',         icon: 'Presentation',  count: 8  },
  { name: 'Productivity & Automation',      slug: 'productivity',          icon: 'Zap',           count: 7  },
  { name: 'Research & Analysis',            slug: 'research',              icon: 'Search',        count: 5  },
  { name: 'Notebooks',                      slug: 'notebooks',             icon: 'BookOpen',      count: 10 },
  { name: 'Competitive Analysis',           slug: 'competitive',           icon: 'Trophy',        count: 21 },
  { name: 'Travel',                         slug: 'travel',                icon: 'Plane',         count: 11 },
  { name: 'Meeting Recordings',             slug: 'meetings',              icon: 'Video',         count: 1  },
  { name: 'Personal Productivity',          slug: 'personal-productivity', icon: 'Target',        count: 1  },
  { name: 'Cowork',                         slug: 'cowork',                icon: 'Bot',           count: 6  },
]
